from __future__ import annotations

from .schema import AgentSpec

AGENT_SPECS: dict[str, AgentSpec] = {
    "ask": AgentSpec(
        id="ask",
        label="Ask",
        role="conversation",
        capabilities=["repo-inspection", "discussion", "status-answering"],
        can_write=False,
        default_runner="auto",
        when_to_use=["plain questions", "project status questions", "explanations"],
        when_not_to_use=["requested source edits", "requested git operations"],
        required_outputs=["answer"],
        handoff_contract="Answer directly without changing project files.",
    ),
    "pm": AgentSpec(
        id="pm",
        label="PM",
        role="clarification",
        capabilities=["scope-clarification", "requirements-triage"],
        can_write=False,
        default_runner="claude",
        when_to_use=["ambiguous change request", "missing acceptance criteria"],
        required_outputs=["scope_decision", "question_if_blocked"],
        handoff_contract="State whether the task is clear or what decision is needed.",
    ),
    "architect": AgentSpec(
        id="architect",
        label="Architect",
        role="system-design",
        capabilities=["architecture-review", "component-boundaries", "decision-logging"],
        can_write=False,
        default_runner="claude",
        when_to_use=["architecture planning", "large cross-module change", "API/schema design"],
        required_outputs=["architecture_handoff"],
        handoff_contract="Frame constraints and implementation boundaries.",
    ),
    "planner": AgentSpec(
        id="planner",
        label="Planner",
        role="planning",
        capabilities=["plan-writing", "task-breakdown"],
        can_write=False,
        default_runner="claude",
        when_to_use=["explicit planning request", "plan-first workflow"],
        required_outputs=["implementation_plan"],
        handoff_contract="Write a concrete implementation plan for approval or execution.",
    ),
    "lead": AgentSpec(
        id="lead",
        label="Lead",
        role="implementation-lead",
        capabilities=["planning", "code-editing", "tests", "debugging"],
        can_write=True,
        default_runner="codex",
        permissions=["read", "write"],
        when_to_use=["implementation", "bug fix", "refactor", "debugging with code changes"],
        required_outputs=["summary", "changed_files"],
        handoff_contract="Implement the requested change and summarize what changed.",
    ),
    "tester": AgentSpec(
        id="tester",
        label="Tester",
        role="testing",
        capabilities=["build-runner", "test-runner", "lint", "verification"],
        can_write=True,
        default_runner="claude",
        permissions=["read", "write"],
        when_to_use=["after source edits", "verification requested", "debugging"],
        required_outputs=["verdict", "commands", "failure_summary"],
        handoff_contract="Run appropriate checks and emit a pass/fail verdict.",
    ),
    "architecture_reviewer": AgentSpec(
        id="architecture_reviewer",
        label="Architecture Reviewer",
        role="specialist-review",
        capabilities=["architecture-risk", "boundary-review", "compatibility"],
        can_write=False,
        default_runner="claude",
        when_to_use=["API changes", "schema changes", "module boundary changes"],
        required_outputs=["verdict", "observations", "blocking_findings"],
        handoff_contract="Review architecture compatibility and boundaries.",
    ),
    "security_reviewer": AgentSpec(
        id="security_reviewer",
        label="Security Reviewer",
        role="specialist-review",
        capabilities=["auth", "secrets", "injection", "trust-boundaries", "unsafe-shell", "payment-risk"],
        can_write=False,
        default_runner="claude",
        when_to_use=["auth changes", "payment changes", "secret handling", "unsafe shell or file operations"],
        when_not_to_use=["copy-only UI changes", "local styling changes with no data or auth impact"],
        required_outputs=["verdict", "risks", "blocking_findings"],
        handoff_contract="Review security risk and emit a structured verdict.",
    ),
    "performance_reviewer": AgentSpec(
        id="performance_reviewer",
        label="Performance Reviewer",
        role="specialist-review",
        capabilities=["latency-review", "render-performance", "polling", "resource-use"],
        can_write=False,
        default_runner="claude",
        when_to_use=["socket changes", "polling changes", "large render paths", "expensive loops"],
        required_outputs=["verdict", "performance_risks"],
        handoff_contract="Review runtime performance risk and emit a verdict.",
    ),
    "maintainability_reviewer": AgentSpec(
        id="maintainability_reviewer",
        label="Maintainability Reviewer",
        role="specialist-review",
        capabilities=["code-health", "testability", "shared-logic", "parser-risk"],
        can_write=False,
        default_runner="claude",
        when_to_use=["shared parser changes", "broad refactors", "duplicated logic", "complex state handling"],
        required_outputs=["verdict", "maintainability_risks"],
        handoff_contract="Review maintainability and extension risk.",
    ),
    "teammate": AgentSpec(
        id="teammate",
        label="Teammate",
        role="final-reviewer",
        capabilities=["final-review", "spec-checking", "risk-analysis"],
        can_write=False,
        default_runner="claude",
        when_to_use=["final sign-off", "multi-agent implementation review"],
        required_outputs=["verdict", "summary"],
        handoff_contract="Provide final implementation review and approval status.",
    ),
    "summarizer": AgentSpec(
        id="summarizer",
        label="Summarizer",
        role="memory",
        capabilities=["context-compression", "project-memory", "lessons"],
        can_write=True,
        default_runner="claude",
        permissions=["read", "write"],
        when_to_use=["task completed", "durable memory update needed"],
        required_outputs=["memory_update"],
        handoff_contract="Update durable project memory after task completion.",
    ),
    "git": AgentSpec(
        id="git",
        label="Git",
        role="git-operation",
        capabilities=["git-status", "git-commit", "git-push", "git-stash", "git-tag"],
        can_write=True,
        default_runner="codex",
        permissions=["read", "write", "git"],
        when_to_use=["direct git operation"],
        required_outputs=["git_result"],
        handoff_contract="Run the requested git operation and report the result.",
    ),
    "decomposer": AgentSpec(
        id="decomposer",
        label="Decomposer",
        role="decomposition",
        capabilities=["domain-analysis", "lane-planning"],
        can_write=False,
        default_runner="claude",
        when_to_use=["large task with independent domains"],
        required_outputs=["lanes"],
        handoff_contract="Identify safe independent implementation lanes.",
    ),
}


def agent_spec(agent_id: str) -> AgentSpec | None:
    return AGENT_SPECS.get(agent_id)


def registry_as_legacy() -> dict[str, dict[str, object]]:
    """Expose AgentSpec data in the shape used by legacy manifest code."""
    return {
        agent_id: {
            "label": spec.label,
            "role": spec.role,
            "capabilities": spec.capabilities,
            "prompt": agent_id,
            "sandbox": "workspace-write" if spec.can_write else "read-only",
            "default_runner": spec.default_runner,
        }
        for agent_id, spec in AGENT_SPECS.items()
    }
